//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace onlinesms.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class professionaldetail
    {
        public int prof_id { get; set; }
        public string prof_qualification { get; set; }
        public string prof_school { get; set; }
        public string prof_college { get; set; }
        public string prof_status { get; set; }
        public string prof_organiztion { get; set; }
        public string prof_designation { get; set; }
        public int user_id { get; set; }
    
        public virtual user user { get; set; }
    }
}
